name: ICT304
channels:
  - defaults
dependencies:
  - python=3.10
  - blas=1.0=openblas
  - bottleneck=1.4.2
  - bzip2
  - ca-certificates
  - cairo
  - cycler
  - expat
  - fontconfig
  - freetype
  - harfbuzz
  - icu
  - jpeg
  - kiwisolver
  - lcms2
  - lerc
  - libdeflate
  - libffi
  - libopenblas
  - libopenjpeg
  - libpng
  - libtiff
  - libwebp-base
  - libxcb
  - libxml2
  - lz4-c
  - matplotlib-base=3.10
  - ncurses
  - numexpr
  - openssl
  - packaging
  - pandas=2.3
  - pcre2
  - pillow
  - pip
  - pixman
  - python-dateutil
  - python-tzdata
  - pytz
  - readline
  - seaborn=0.13
  - setuptools
  - six
  - sqlite
  - tk
  - tzdata
  - wheel
  - xz
  - zlib
  - zstd
  - pip:
      - absl-py==2.4.0
      - attrs==26.1.0
      - certifi
      - cffi
      - charset-normalizer
      - contourpy
      - filelock
      - flatbuffers
      - fonttools
      - fsspec
      - idna
      - jinja2
      - joblib
      - markupsafe
      - mediapipe==0.10.9
      - mpmath
      - networkx
      - numpy==2.2.6
      - opencv-contrib-python==4.13.0.92
      - opencv-python==4.13.0.92
      - polars==1.38.1
      - protobuf==3.20.3
      - psutil
      - pycparser
      - pyparsing
      - pyyaml
      - requests
      - scikit-learn
      - scipy
      - sounddevice
      - sympy
      - threadpoolctl
      - torch==2.10.0
      - torchvision==0.25.0
      - typing-extensions
      - ultralytics==8.4.21
      - ultralytics-thop
      - urllib3